export const LOCAL_WEAPONS = [
    // --- SIMPLE MELEE ---
    { name: "Club", cost: "1 sp", damage: "1d4", damageType: "Bludgeoning", weight: "2 lb.", properties: "Light, Slow", mastery: "Slow", category: "Simple Melee" },
    { name: "Dagger", cost: "2 gp", damage: "1d4", damageType: "Piercing", weight: "1 lb.", properties: "Finesse, Light, Thrown (Range 20/60), Nick", mastery: "Nick", category: "Simple Melee" },
    { name: "Greatclub", cost: "2 sp", damage: "1d8", damageType: "Bludgeoning", weight: "10 lb.", properties: "Two-Handed, Push", mastery: "Push", category: "Simple Melee" },
    { name: "Handaxe", cost: "5 gp", damage: "1d6", damageType: "Slashing", weight: "2 lb.", properties: "Light, Thrown (Range 20/60), Vex", mastery: "Vex", category: "Simple Melee" },
    { name: "Javelin", cost: "5 sp", damage: "1d6", damageType: "Piercing", weight: "2 lb.", properties: "Thrown (Range 30/120), Slow", mastery: "Slow", category: "Simple Melee" },
    { name: "Light Hammer", cost: "2 gp", damage: "1d4", damageType: "Bludgeoning", weight: "2 lb.", properties: "Light, Thrown (Range 20/60), Nick", mastery: "Nick", category: "Simple Melee" },
    { name: "Mace", cost: "5 gp", damage: "1d6", damageType: "Bludgeoning", weight: "4 lb.", properties: "Sap", mastery: "Sap", category: "Simple Melee" },
    { name: "Quarterstaff", cost: "2 sp", damage: "1d6", damageType: "Bludgeoning", weight: "4 lb.", properties: "Versatile (1d8), Topple", mastery: "Topple", category: "Simple Melee" },
    { name: "Sickle", cost: "1 gp", damage: "1d4", damageType: "Slashing", weight: "2 lb.", properties: "Light, Nick", mastery: "Nick", category: "Simple Melee" },
    { name: "Spear", cost: "1 gp", damage: "1d6", damageType: "Piercing", weight: "3 lb.", properties: "Thrown (Range 20/60), Versatile (1d8), Sap", mastery: "Sap", category: "Simple Melee" },

    // --- SIMPLE RANGED ---
    { name: "Dart", cost: "5 cp", damage: "1d4", damageType: "Piercing", weight: "1/4 lb.", properties: "Finesse, Thrown (Range 20/60), Vex", mastery: "Vex", category: "Simple Ranged" },
    { name: "Light Crossbow", cost: "25 gp", damage: "1d8", damageType: "Piercing", weight: "5 lb.", properties: "Ammunition (Range 80/320; Bolt), Loading, Two-Handed, Slow", mastery: "Slow", category: "Simple Ranged" },
    { name: "Shortbow", cost: "25 gp", damage: "1d6", damageType: "Piercing", weight: "2 lb.", properties: "Ammunition (Range 80/320; Arrow), Two-Handed, Vex", mastery: "Vex", category: "Simple Ranged" },
    { name: "Sling", cost: "1 sp", damage: "1d4", damageType: "Bludgeoning", weight: "-", properties: "Ammunition (Range 30/120; Bullet), Slow", mastery: "Slow", category: "Simple Ranged" },

    // --- MARTIAL MELEE ---
    { name: "Battleaxe", cost: "10 gp", damage: "1d8", damageType: "Slashing", weight: "4 lb.", properties: "Versatile (1d10), Topple", mastery: "Topple", category: "Martial Melee" },
    { name: "Flail", cost: "10 gp", damage: "1d8", damageType: "Bludgeoning", weight: "2 lb.", properties: "Sap", mastery: "Sap", category: "Martial Melee" },
    { name: "Glaive", cost: "20 gp", damage: "1d10", damageType: "Slashing", weight: "6 lb.", properties: "Heavy, Reach, Two-Handed, Graze", mastery: "Graze", category: "Martial Melee" },
    { name: "Greataxe", cost: "30 gp", damage: "1d12", damageType: "Slashing", weight: "7 lb.", properties: "Heavy, Two-Handed, Cleave", mastery: "Cleave", category: "Martial Melee" },
    { name: "Greatsword", cost: "50 gp", damage: "2d6", damageType: "Slashing", weight: "6 lb.", properties: "Heavy, Two-Handed, Graze", mastery: "Graze", category: "Martial Melee" },
    { name: "Halberd", cost: "20 gp", damage: "1d10", damageType: "Slashing", weight: "6 lb.", properties: "Heavy, Reach, Two-Handed, Cleave", mastery: "Cleave", category: "Martial Melee" },
    { name: "Lance", cost: "10 gp", damage: "1d10", damageType: "Piercing", weight: "6 lb.", properties: "Heavy, Reach, Two-Handed (unless mounted), Topple", mastery: "Topple", category: "Martial Melee" },
    { name: "Longsword", cost: "15 gp", damage: "1d8", damageType: "Slashing", weight: "3 lb.", properties: "Versatile (1d10), Sap", mastery: "Sap", category: "Martial Melee" },
    { name: "Maul", cost: "10 gp", damage: "2d6", damageType: "Bludgeoning", weight: "10 lb.", properties: "Heavy, Two-Handed, Topple", mastery: "Topple", category: "Martial Melee" },
    { name: "Morningstar", cost: "15 gp", damage: "1d8", damageType: "Piercing", weight: "4 lb.", properties: "Sap", mastery: "Sap", category: "Martial Melee" },
    { name: "Pike", cost: "5 gp", damage: "1d10", damageType: "Piercing", weight: "18 lb.", properties: "Heavy, Reach, Two-Handed, Push", mastery: "Push", category: "Martial Melee" },
    { name: "Rapier", cost: "25 gp", damage: "1d8", damageType: "Piercing", weight: "2 lb.", properties: "Finesse, Vex", mastery: "Vex", category: "Martial Melee" },
    { name: "Scimitar", cost: "25 gp", damage: "1d6", damageType: "Slashing", weight: "3 lb.", properties: "Finesse, Light, Nick", mastery: "Nick", category: "Martial Melee" },
    { name: "Shortsword", cost: "10 gp", damage: "1d6", damageType: "Piercing", weight: "2 lb.", properties: "Finesse, Light, Vex", mastery: "Vex", category: "Martial Melee" },
    { name: "Trident", cost: "5 gp", damage: "1d8", damageType: "Piercing", weight: "4 lb.", properties: "Thrown (Range 20/60), Versatile (1d10), Topple", mastery: "Topple", category: "Martial Melee" },
    { name: "Warhammer", cost: "15 gp", damage: "1d8", damageType: "Bludgeoning", weight: "2 lb.", properties: "Versatile (1d10), Push", mastery: "Push", category: "Martial Melee" },
    { name: "War Pick", cost: "5 gp", damage: "1d8", damageType: "Piercing", weight: "2 lb.", properties: "Versatile (1d10), Sap", mastery: "Sap", category: "Martial Melee" },
    { name: "Whip", cost: "2 gp", damage: "1d4", damageType: "Slashing", weight: "3 lb.", properties: "Finesse, Reach, Slow", mastery: "Slow", category: "Martial Melee" },

    // --- MARTIAL RANGED ---
    { name: "Blowgun", cost: "10 gp", damage: "1", damageType: "Piercing", weight: "1 lb.", properties: "Ammunition (Range 25/100; Needle), Loading, Vex", mastery: "Vex", category: "Martial Ranged" },
    { name: "Hand Crossbow", cost: "75 gp", damage: "1d6", damageType: "Piercing", weight: "3 lb.", properties: "Ammunition (Range 30/120; Bolt), Light, Loading, Vex", mastery: "Vex", category: "Martial Ranged" },
    { name: "Heavy Crossbow", cost: "50 gp", damage: "1d10", damageType: "Piercing", weight: "18 lb.", properties: "Ammunition (Range 100/400; Bolt), Heavy, Loading, Two-Handed, Push", mastery: "Push", category: "Martial Ranged" },
    { name: "Longbow", cost: "50 gp", damage: "1d8", damageType: "Piercing", weight: "2 lb.", properties: "Ammunition (Range 150/600; Arrow), Heavy, Two-Handed, Slow", mastery: "Slow", category: "Martial Ranged" },
    { name: "Musket", cost: "500 gp", damage: "1d12", damageType: "Piercing", weight: "10 lb.", properties: "Ammunition (Range 40/120; Bullet), Loading, Two-Handed, Slow", mastery: "Slow", category: "Martial Ranged" },
    { name: "Pistol", cost: "250 gp", damage: "1d10", damageType: "Piercing", weight: "3 lb.", properties: "Ammunition (Range 30/90; Bullet), Loading, Vex", mastery: "Vex", category: "Martial Ranged" }
];

export const LOCAL_ARMOR = [
    // --- LIGHT ARMOR ---
    { name: "Padded Armor", cost: "5 gp", ac: "11", formula: "11 + Dex", stealthDis: true, weight: "8 lb.", category: "Light" },
    { name: "Leather Armor", cost: "10 gp", ac: "11", formula: "11 + Dex", stealthDis: false, weight: "10 lb.", category: "Light" },
    { name: "Studded Leather Armor", cost: "45 gp", ac: "12", formula: "12 + Dex", stealthDis: false, weight: "13 lb.", category: "Light" },

    // --- MEDIUM ARMOR ---
    { name: "Hide Armor", cost: "10 gp", ac: "12", formula: "12 + Dex (max 2)", stealthDis: false, weight: "12 lb.", category: "Medium" },
    { name: "Chain Shirt", cost: "50 gp", ac: "13", formula: "13 + Dex (max 2)", stealthDis: false, weight: "20 lb.", category: "Medium" },
    { name: "Scale Mail", cost: "50 gp", ac: "14", formula: "14 + Dex (max 2)", stealthDis: true, weight: "45 lb.", category: "Medium" },
    { name: "Breastplate", cost: "400 gp", ac: "14", formula: "14 + Dex (max 2)", stealthDis: false, weight: "20 lb.", category: "Medium" },
    { name: "Half Plate Armor", cost: "750 gp", ac: "15", formula: "15 + Dex (max 2)", stealthDis: true, weight: "40 lb.", category: "Medium" },

    // --- HEAVY ARMOR ---
    { name: "Ring Mail", cost: "30 gp", ac: "14", formula: "14", stealthDis: true, weight: "40 lb.", category: "Heavy" },
    { name: "Chain Mail", cost: "75 gp", ac: "16", formula: "16", stealthDis: true, weight: "55 lb.", category: "Heavy", strengthReq: 13 },
    { name: "Splint Armor", cost: "200 gp", ac: "17", formula: "17", stealthDis: true, weight: "60 lb.", category: "Heavy", strengthReq: 15 },
    { name: "Plate Armor", cost: "1,500 gp", ac: "18", formula: "18", stealthDis: true, weight: "65 lb.", category: "Heavy", strengthReq: 15 },

    // --- SHIELD ---
    { name: "Shield", cost: "10 gp", ac: "+2", formula: "+2", stealthDis: false, weight: "6 lb.", category: "Shield" }
];

export const LOCAL_GEAR = [
    { name: "Acid", cost: "25 gp", weight: "1 lb.", description: "As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the acid as an improvised weapon. On a hit, the target takes 2d6 acid damage." },
    { name: "Alchemist's Fire", cost: "50 gp", weight: "1 lb.", description: "This sticky, adhesive fluid ignites when exposed to air. As an action, you can throw this flask up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the alchemist's fire as an improvised weapon. On a hit, the target takes 1d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 10 Dexterity check to extinguish the flames." },
    { name: "Ammunition (Arrows)", cost: "1 gp", weight: "1 lb.", description: "Arrows for a bow. Bundle of 20." },
    { name: "Ammunition (Bolts)", cost: "1 gp", weight: "1.5 lb.", description: "Crossbow bolts. Case of 20." },
    { name: "Ammunition (Bullets)", cost: "4 cp", weight: "1.5 lb.", description: "Sling bullets. Bag of 20." },
    { name: "Ammunition (Needles)", cost: "1 gp", weight: "1 lb.", description: "Blowgun needles. 50 count." },
    { name: "Antitoxin", cost: "50 gp", weight: "-", description: "A creature that drinks this vial of liquid gains advantage on saving throws against poison for 1 hour. It confers no benefit to undead or constructs." },
    { name: "Arcane Focus", cost: "5-20 gp", weight: "1-3 lb.", description: "An arcane focus is a special item designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus." },
    { name: "Backpack", cost: "2 gp", weight: "5 lb.", description: "A backpack can hold 1 cubic foot or 30 pounds of gear. You can also strap items, such as a bedroll or a coil of rope, to the outside of a backpack." },
    { name: "Ball Bearings", cost: "1 gp", weight: "2 lb.", description: "As an action, you can spill these tiny metal balls from their pouch to cover a level, square area that is 10 feet on a side. A creature moving across the covered area must succeed on a DC 10 Dexterity saving throw or fall prone. A creature moving through the area at half speed doesn't need to make the save." },
    { name: "Barrel", cost: "2 gp", weight: "70 lb.", description: "Capacity: 40 gallons liquid, 4 cubic feet solid." },
    { name: "Basket", cost: "4 sp", weight: "2 lb.", description: "Capacity: 2 cubic feet/40 pounds." },
    { name: "Bedroll", cost: "1 gp", weight: "7 lb.", description: "You never know where you're going to sleep." },
    { name: "Bell", cost: "1 gp", weight: "-", description: "A standard bell." },
    { name: "Blanket", cost: "5 sp", weight: "3 lb.", description: "A thick, quilted, blanket." },
    { name: "Block and Tackle", cost: "1 gp", weight: "5 lb.", description: "A set of pulleys with a cable threaded through them and a hook to attach to objects, a block and tackle allows you to hoist up to four times the weight you can normally lift." },
    { name: "Book", cost: "25 gp", weight: "5 lb.", description: "A book might contain poetry, historical accounts, information pertaining to a particular field of lore, diagrams and notes on gnomish contraptions, or just about anything else that can be represented using text or pictures." },
    { name: "Bottle, Glass", cost: "2 gp", weight: "2 lb.", description: "Capacity: 1.5 pints liquid." },
    { name: "Bucket", cost: "5 cp", weight: "2 lb.", description: "Capacity: 3 gallons liquid, 1/2 cubic foot solid." },
    { name: "Burglar's Pack", cost: "16 gp", weight: "47 lb.", description: "Includes a backpack, a bag of 1,000 ball bearings, 10 feet of string, a bell, 5 candles, a crowbar, a hammer, 10 pitons, a hooded lantern, 2 flasks of oil, 5 days rations, a tinderbox, and a waterskin. The pack also has 50 feet of hempen rope strapped to the side of it." },
    { name: "Caltrops", cost: "1 gp", weight: "2 lb.", description: "As an action, you can spread a bag of caltrops to cover a square area that is 5 feet on a side. Any creature that enters the area must succeed on a DC 15 Dexterity saving throw or stop moving this turn and take 1 piercing damage. Taking this damage reduces the creature's walking speed by 10 feet until the creature regains at least 1 hit point." },
    { name: "Candle", cost: "1 cp", weight: "-", description: "For 1 hour, a candle sheds bright light in a 5-foot radius and dim light for an additional 5 feet." },
    { name: "Case, Crossbow Bolt", cost: "1 gp", weight: "1 lb.", description: "This wooden case can hold up to twenty crossbow bolts." },
    { name: "Case, Map or Scroll", cost: "1 gp", weight: "1 lb.", description: "This cylindrical leather case can hold up to ten rolled-up sheets of paper or parchment." },
    { name: "Chain (10 feet)", cost: "5 gp", weight: "10 lb.", description: "A chain has 10 hit points. It can be burst with a successful DC 20 Strength check." },
    { name: "Chest", cost: "5 gp", weight: "25 lb.", description: "Capacity: 12 cubic feet/300 pounds." },
    { name: "Climber's Kit", cost: "25 gp", weight: "12 lb.", description: "A climber's kit includes special pitons, boot tips, gloves, and a harness. You can use the climber's kit as an action to anchor yourself; when you do, you can't fall more than 25 feet from the point where you anchored yourself, and you can't climb more than 25 feet away from that point without undoing the anchor." },
    { name: "Clothes, Fine", cost: "15 gp", weight: "6 lb.", description: "Expensive clothes for wealthy or noble characters." },
    { name: "Clothes, Traveler's", cost: "2 gp", weight: "4 lb.", description: "Standard clothing for travel." },
    { name: "Component Pouch", cost: "25 gp", weight: "2 lb.", description: "A component pouch is a small, watertight leather belt pouch that has compartments to hold all the material components and other special items you need to cast your spells, except for those components that have a specific cost." },
    { name: "Costume", cost: "5 gp", weight: "4 lb.", description: "Clothing for a specific role or disguise." },
    { name: "Crowbar", cost: "2 gp", weight: "5 lb.", description: "Using a crowbar grants advantage to Strength checks where the crowbar's leverage can be applied." },
    { name: "Diplomat's Pack", cost: "39 gp", weight: "46 lb.", description: "Includes a chest, 2 cases for maps and scrolls, a set of fine clothes, a bottle of ink, an ink pen, a lamp, 2 flasks of oil, 5 sheets of paper, a vial of perfume, sealing wax, and soap." },
    { name: "Druidic Focus", cost: "1-10 gp", weight: "-", description: "A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals." },
    { name: "Dungeoneer's Pack", cost: "12 gp", weight: "61 lb.", description: "Includes a backpack, a crowbar, a hammer, 10 pitons, 10 torches, a tinderbox, 10 days of rations, and a waterskin. The pack also has 50 feet of hempen rope strapped to the side of it." },
    { name: "Entertainer's Pack", cost: "40 gp", weight: "38 lb.", description: "Includes a backpack, a bedroll, 2 costumes, 5 candles, 5 days of rations, a waterskin, and a disguise kit." },
    { name: "Explorer's Pack", cost: "10 gp", weight: "59 lb.", description: "Includes a backpack, a bedroll, a mess kit, a tinderbox, 10 torches, 10 days of rations, and a waterskin. The pack also has 50 feet of hempen rope strapped to the side of it." },
    { name: "Flask", cost: "2 cp", weight: "1 lb.", description: "Capacity: 1 pint liquid." },
    { name: "Grappling Hook", cost: "2 gp", weight: "4 lb.", description: "When tied to the end of a rope, a grappling hook can secure the rope to a battlement, window ledge, tree limb, or other protrusion." },
    { name: "Healer's Kit", cost: "5 gp", weight: "3 lb.", description: "This kit is a leather pouch containing bandages, salves, and splints. The kit has ten uses. As an action, you can expend one use of the kit to stabilize a creature that has 0 hit points, without needing to make a Wisdom (Medicine) check." },
    { name: "Holy Symbol", cost: "5 gp", weight: "1 lb.", description: "A holy symbol is a representation of a god or pantheon." },
    { name: "Holy Water", cost: "25 gp", weight: "1 lb.", description: "As an action, you can splash the contents of this flask onto a creature within 5 feet of you or throw the flask up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the holy water as an improvised weapon. If the target is a fiend or undead, it takes 2d6 radiant damage." },
    { name: "Hunting Trap", cost: "5 gp", weight: "25 lb.", description: "When you use your action to set it, this trap forms a saw-toothed steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to an immobile object, such as a tree or a spike driven into the ground." },
    { name: "Ink (1 ounce bottle)", cost: "10 gp", weight: "-", description: "Ink for writing." },
    { name: "Ink Pen", cost: "2 cp", weight: "-", description: "A wooden pen with a metal nib." },
    { name: "Jug", cost: "2 cp", weight: "4 lb.", description: "Capacity: 1 gallon liquid." },
    { name: "Ladder (10-foot)", cost: "1 sp", weight: "25 lb.", description: "A standard wooden ladder." },
    { name: "Lamp", cost: "5 sp", weight: "1 lb.", description: "A lamp casts bright light in a 15-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil." },
    { name: "Lantern, Bullseye", cost: "10 gp", weight: "2 lb.", description: "A bullseye lantern casts bright light in a 60-foot cone and dim light for an additional 60 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil." },
    { name: "Lantern, Hooded", cost: "5 gp", weight: "2 lb.", description: "A hooded lantern casts bright light in a 30-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil. As an action, you can lower the hood, reducing the light to dim light in a 5-foot radius." },
    { name: "Lock", cost: "10 gp", weight: "1 lb.", description: "A key is provided with the lock. Without the key, a creature proficient with thieves' tools can pick this lock with a successful DC 15 Dexterity check." },
    { name: "Magnifying Glass", cost: "100 gp", weight: "-", description: "This lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires." },
    { name: "Manacles", cost: "2 gp", weight: "6 lb.", description: "These metal restraints can bind a Small or Medium creature. Escaping the manacles requires a successful DC 20 Dexterity check. Breaking them requires a successful DC 20 Strength check." },
    { name: "Map", cost: "-", weight: "-", description: "A map of a city, dungeon, or land." },
    { name: "Mirror, Steel", cost: "5 gp", weight: "0.5 lb.", description: "A polished steel mirror." },
    { name: "Net", cost: "1 gp", weight: "3 lb.", description: "A Large or smaller creature hit by a net is restrained until it is freed. A net has no effect on creatures that are formless, or creatures that are Huge or larger. A creature can use its action to make a DC 10 Strength check, freeing itself or another creature within its reach on a success." },
    { name: "Oil (flask)", cost: "1 sp", weight: "1 lb.", description: "Oil usually comes in a clay flask that holds 1 pint. As an action, you can splash the oil in this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact." },
    { name: "Paper (one sheet)", cost: "2 sp", weight: "-", description: "Standard paper." },
    { name: "Parchment (one sheet)", cost: "1 sp", weight: "-", description: "Standard parchment." },
    { name: "Perfume (vial)", cost: "5 gp", weight: "-", description: "A fragrant scent." },
    { name: "Poison, Basic (vial)", cost: "100 gp", weight: "-", description: "You can use the poison in this vial to coat one slashing or piercing weapon or up to three pieces of ammunition. Applying the poison takes an action. A creature hit by the poisoned weapon or ammunition must make a DC 10 Constitution saving throw or take 1d4 poison damage." },
    { name: "Pole (10-foot)", cost: "5 cp", weight: "7 lb.", description: "A standard wooden pole." },
    { name: "Pot, Iron", cost: "2 gp", weight: "10 lb.", description: "Capacity: 1 gallon liquid." },
    { name: "Potion of Healing", cost: "50 gp", weight: "0.5 lb.", description: "A character who drinks the magical red fluid in this vial regains 2d4 + 2 hit points." },
    { name: "Pouch", cost: "5 sp", weight: "1 lb.", description: "A cloth or leather pouch can hold up to 20 sling bullets or 50 blowgun needles, among other things. A compartmentalized pouch for holding spell components is called a component pouch." },
    { name: "Priest's Pack", cost: "19 gp", weight: "25 lb.", description: "Includes a backpack, a blanket, 10 candles, a tinderbox, an alms box, 2 blocks of incense, a censer, vestments, 2 days of rations, and a waterskin." },
    { name: "Quiver", cost: "1 gp", weight: "1 lb.", description: "Can hold up to 20 arrows." },
    { name: "Ram, Portable", cost: "4 gp", weight: "35 lb.", description: "You can use a portable ram to break down doors. When doing so, you gain a +4 bonus on the Strength check. One other character can help you use the ram, giving you advantage on this check." },
    { name: "Rations (1 day)", cost: "5 sp", weight: "2 lb.", description: "Dry food for travel." },
    { name: "Robe", cost: "1 gp", weight: "4 lb.", description: "Standard robe." },
    { name: "Rope, Hempen (50 feet)", cost: "1 gp", weight: "10 lb.", description: "Standard rope. It has 2 hit points and can be burst with a DC 17 Strength check." },
    { name: "Rope, Silk (50 feet)", cost: "10 gp", weight: "5 lb.", description: "Stronger and lighter than hemp. It has 4 hit points and can be burst with a DC 17 Strength check." },
    { name: "Sack", cost: "1 cp", weight: "0.5 lb.", description: "Capacity: 1 cubic foot/30 pounds." },
    { name: "Scholar's Pack", cost: "40 gp", weight: "11 lb.", description: "Includes a backpack, a book of lore, a bottle of ink, an ink pen, 10 sheets of parchment, a little bag of sand, and a small knife." },
    { name: "Shovel", cost: "2 gp", weight: "5 lb.", description: "Used for digging." },
    { name: "Signal Whistle", cost: "5 cp", weight: "-", description: "A small whistle used for signaling." },
    { name: "Spikes, Iron (10)", cost: "1 gp", weight: "5 lb.", description: "Used for climbing or securing doors." },
    { name: "Spyglass", cost: "1000 gp", weight: "1 lb.", description: "Objects viewed through a spyglass are magnified to twice their size." },
    { name: "String (10 feet)", cost: "-", weight: "-", description: "Simple string." },
    { name: "Tent, Two-person", cost: "2 gp", weight: "20 lb.", description: "A simple canvas tent." },
    { name: "Tinderbox", cost: "5 sp", weight: "1 lb.", description: "This small container holds flint, fire steel, and tinder (usually dry cloth soaked in light oil) used to kindle a fire. Using it to light a torch - or anything else with abundant, exposed fuel - takes an action." },
    { name: "Torch", cost: "1 cp", weight: "1 lb.", description: "A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage." },
    { name: "Vial", cost: "1 gp", weight: "-", description: "Capacity: 4 ounces liquid." },
    { name: "Waterskin", cost: "2 sp", weight: "5 lb. (full)", description: "Capacity: 4 pints liquid." },
];